### ISSUE TITLE
Initial implementation of fastchat-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/fastchat-container#1]
## Description

This issue tracks the initial implementation of fastchat-container, a Docker container for running FastChat models.

## Tasks

- [ ] Create Dockerfile to build container image
  - [x] Base image: Ubuntu or Debian
  - [ ] Install FastChat and dependencies
  - [ ] Expose ports for HTTP server
- [ ] Configure entrypoint script 
  - [ ] Load FastChat model on start
  - [ ] Start HTTP server
  - [ ] Graceful shutdown on SIGTERM
- [ ] Create docker-compose file to run container
  - [ ] Map host ports to container
  - [ ] Mount volumes for data persistence
  - [ ] Environment variables for configuration
- [ ] Write documentation
  - [ ] Building and running container
  - [ ] Persistent storage
  - [ ] Environment variables
  - [ ] Exposed ports
  - [ ] Logging
  - [ ] Limitations
- [ ] Add CI to build and test container

## Related Issues

- Track performance optimizations in separate issues
- Persistent storage for models
